// src/components/SideBar.vue
<template>
  <div id="aside">
    <b-button id="toggle-btn" v-b-toggle.sidebar-variant>
      <img src="../assets/img/menu-toggle.png" />
    </b-button>
    <b-sidebar
      id="sidebar-variant"
      bg-variant="light"
      text-variant="dark"
      backdrop
      shadow
    >
      <b-container class="profile-img">
        <b-img
          :src="require('../assets/img/profile.png')"
          rounded="circle"
          fluid-grow
          alt="Fluid-grow image"
        >
        </b-img>
      </b-container>
      <div class="title">
        <h1 class="first-row"><span>epilef</span></h1>
        <h1 class="second-row"><span>rodriguez</span></h1>
        <h2><span>Design & Develop</span></h2>
      </div>
      <div class="quote">
        <p>Full=Stack Software Engineer - Looking for the next Challenge.</p>
        <!-- <h2>This is a work in progress, so don't judge and check out the <a href="https://github.com/Khanos/khanos.github.io" target="_blank">github</a> and <a href="https://trello.com/b/KdkP1DtZ" target="_blank">trello</a> of the project.</h2> -->
      </div>
      <div class="nav-menu">
        <ol>
          <li>
            <router-link to="/">Home </router-link>
            <img class="img-arrow" src="../assets/img/arrow-right.png" />
          </li>
          <li>
            <router-link to="/what">What i do </router-link>
            <img class="img-arrow" src="../assets/img/arrow-right.png" />
          </li>
          <!-- <li>
            <router-link to="/how">How i do it </router-link>
            <img class="img-arrow" src="../assets/img/arrow-right.png" />
          </li> -->
          <li>
            <router-link to="/who">Who am i </router-link>
            <img class="img-arrow" src="../assets/img/arrow-right.png" />
          </li>
        </ol>
      </div>
    </b-sidebar>
  </div>
</template>

<script>
export default {
  name: 'SideBar',
};
</script>

<style scoped>
#aside #toggle-btn {
  position: absolute;
  left: 10px;
  top: 10px;
  background-color: transparent;
  border-color: transparent;
  z-index: 1000;
}
#aside #toggle-btn:focus,
#aside #toggle-btn.focus {
  box-shadow: none !important;
}
#aside #toggle-btn img {
  width: 40px;
}
#aside {
  background-color: #fdfffc;
  align-self: stretch;
  display: flex;
  flex-direction: column;
  align-items: center;
}
#aside .profile-img {
  width: 70%;
}
#aside .title {
  width: 100%;
  margin-top: 10%;
  margin-bottom: 10%;
  text-align: center;
}

#aside .title h1 {
  color: #fdfffc;
  font-size: 2vw;
  letter-spacing: 5px;
}

#aside .title h2 {
  font-family: "Raleway", sans-serif;
  font-size: 1.4vw;
  letter-spacing: 5px;
}

#aside .title h1.first-row span {
  background-color: #4d4444;
  position: relative;
  right: 20%;
}

#aside .title h1.second-row span {
  background-color: #4d4444;
  position: relative;
  left: 10%;
}

#aside .title h1.second-row::first-letter {
  color: #f800ae;
}

#aside .nav-menu {
  position: absolute;
  bottom: 0;
  right: 0;
}

#aside img.img-arrow {
  width: 0.8vw;
  margin-left: 8px;
  position: relative;
  top: -5px;
}

#aside ol {
  width: 100%;
  text-align: right;
  list-style: none;
  flex-grow: 2;
  display: flex;
  flex-direction: column;
  justify-content: center;
  padding: 0px;
}

#aside ol li {
  padding: 2vh 10px;
}

#aside ol li a {
  text-decoration: none;
  color: #4d4444;
  font-family: "Roboto-Thin", sans-serif;
  font-size: 1.8vw;
  font-weight: bold;
}
#aside ol li a.router-link-exact-active {
  background-color: #4d4444;
  color: #ffffff !important;
  padding-left: 6vw;
}

@media screen and (max-width: 700px) {
  #aside #toggle-btn {
    position: absolute;
    left: 10px;
    top: 10px;
    background-color: transparent;
    border-color: transparent;
  }
  #aside #toggle-btn img {
    width: 40px;
  }
  #aside {
    height: 100%;
    width: 70%;
    display: none;
    position: fixed;
    z-index: 10;
    top: 0;
    left: 0;
    overflow-x: hidden;
    transition: 0.5s;
  }

  #aside .title h1 {
    font-size: 4.2vh;
  }

  #aside .title h2 {
    font-size: 2.6vh;
  }

  #aside ol li a {
    font-size: 4vh;
  }

  #aside img.img-arrow {
    width: 1rem;
  }
}
</style>

// components/Sidebar.tsx
import Image from 'next/image'
import Link from 'next/link'
import { useRouter } from 'next/router'

import styles from '@/styles/Sidebar.module.css'
import { useAppContext } from '@/context/appContext';
import { useEffect, useState } from 'react';

export default function Sidebar() {
  const router = useRouter();
  const { sidebar, toggleSidebar, hideSidebar } = useAppContext();
  const [currentRoute, setCurrentRoute] = useState<string>(router.pathname);

  useEffect (() => {
    setCurrentRoute(router.pathname);
  }, [router.pathname]);

  return (
  <>
    { !sidebar.isOpen &&
    <button type='button' className={styles.toggle} onClick={toggleSidebar} >
      <Image 
      src="/img/menu-toggle.png" 
      alt="Toggle button for the side panel"
      width={30}
      height={30}
      />
    </button>
    }
    <div className={`${styles.sidebar}`} style={{
    opacity: !sidebar.isOpen ? "0" : "1",
    display: !sidebar.isOpen ? "none" : "flex",
    }}> 
      <button onClick={toggleSidebar} type="button" aria-label="Close" className={styles.close}>
        <svg viewBox="0 0 16 16" width="1em" height="1em" focusable="false" role="img" aria-label="x" xmlns="http://www.w3.org/2000/svg" fill="currentColor"><g><path fillRule="evenodd" d="M11.854 4.146a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708-.708l7-7a.5.5 0 0 1 .708 0z"></path><path fillRule="evenodd" d="M4.146 4.146a.5.5 0 0 0 0 .708l7 7a.5.5 0 0 0 .708-.708l-7-7a.5.5 0 0 0-.708 0z"></path></g></svg>
      </button>
      <div className={styles.profile}>
        <Image
          src="/img/profile.JPG"
          alt="Profile image of the author"
          width={160}
          height={160}
          priority
        />
      </div>
      <div className={styles.title}>
        <h1 className={styles['first-row']}>
          <span>epilef</span>
        </h1>
        <h1 className={styles['second-row']}>
          <span>rodriguez</span>
        </h1>
        <h2>
          <span>Design &amp; Develop</span>
        </h2>
      </div>
      <div className={styles.quote}>
        <p>Full=Stack Software Engineer - Looking for the next Challenge.</p>
      </div>
      <div className={styles['nav-menu']}>
        <ol className={styles['link-list']}>
          <li className={`${styles['link']} ${currentRoute === '/' ? styles['link-active'] : ''}`}>
            <Link className={styles['text']} href="/" onClick={hideSidebar}>Home </Link>
            <Image src="/img/arrow-right.png" alt="Arrow right" width={20} height={20} />
          </li>
          <li className={`${styles['link']} ${currentRoute === '/what/github' ? styles['link-active'] : ''}`}>
            <Link className={styles['text']} href="/what/github" onClick={hideSidebar}>
              <div>What i do </div>
              <div className={styles['text-subtitle']}>github demo</div>
            </Link>
            <Image src="/img/arrow-right.png" alt="Arrow right" width={20} height={20} />
          </li>
          <li className={`${styles['link']} ${currentRoute === '/what/chatgpt' ? styles['link-active'] : ''}`}>
            <Link className={styles['text']} href="#" onClick={hideSidebar}>
              <div>What i do </div>
              <div className={styles['text-subtitle']}>chatGPT demo</div>
            </Link>
            <Image src="/img/arrow-right.png" alt="Arrow right" width={20} height={20} />
          </li>
          {/* <li className={styles['link']}>
            <Link className={styles['text']} href="#" onClick={hideSidebar}>How i do it </Link>
            <Image src="/img/arrow-right.png" alt="Arrow right" width={20} height={20} />
          </li> */}
          <li className={styles['link']}>
            <Link className={styles['text']} href="/who" onClick={hideSidebar}>Who am i </Link>
            <Image src="/img/arrow-right.png" alt="Arrow right" width={20} height={20} />
          </li>
        </ol>
      </div>
    </div>
  </>
  )
}
